### ISSUE TITLE
DeprecationWarning: URL string parser is deprecated

### ISSUE THREAD

**Issue by DPontes** [sgnn7/deploying_with_docker#3]
Hi I'm following the exercise of Chapter 3 and I get the application server running, and am able to input words in the Words field. I also see the words that I input in the terminal where the application is running.

However, in the browser the words that I input do not show up. I get the output as can be seen in the attached file. 
![screenshot-2018-5-25 docker words](https://user-images.githubusercontent.com/1092418/40547389-05d8c8a0-6032-11e8-8ff2-7ca50165f331.png)

The Warning error output in the terminal is as follows:

_(node:4070) DeprecationWarning: current URL string parser is deprecated, and will be removed in a future version. To use the new parser, pass option { useNewUrlParser: true } to MongoClient.connect._

**Comment by sgnn7** [comment]
Hey @DPontes,
That's an interesting issue. Can you post the terminal output of your application output after you tried inputting a few words?

From what I can guess (and this is a total shot in the dark) can you ensure that these lines are _exactly_ the same as written [here](https://github.com/sgnn7/deploying_with_docker/blob/master/chapter_3/prototype_service/application_server/views/index.pug#L12-L13) including whitespace and equals placement?

**Comment by DPontes** [comment]
Well, your shot in the dark was right on the money. I had `li = word` instead of `li= word` as suggested.
Now I see this:

![image](https://user-images.githubusercontent.com/1092418/40550500-8dcbdd58-603a-11e8-808f-8c7c42472aff.png)

But I'd say that I must have done some similar error somewhere else. I'm used to more forgiving programming languages... :+1: 

Thank you for your quick help. I'd say that this issue can be closed

**Comment by sgnn7** [comment]
@DPontes Great to hear and yeah, templates are notorious for being unforgiving :)

Closing as resolved.
